name: DevSecOps Pipeline with Trivy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Step 2: Set up Java environment
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn clean package
      
    # Step 4: Build Docker image 
    - name: Build Docker image
      run: |
        docker build -t microservice:${{ github.sha }} .

    # Step 5: Run Trivy vulnerability scanner (with `with:` block)
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: microservice:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'HIGH,CRITICAL'
        ignore-unfixed: true

    # Step 6: Upload Trivy scan results to GitHub Security tab
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
